### ISSUE TITLE
Can't create Oracle

### ISSUE THREAD

**Issue by zupino** [gnosis/gnosis.js#90] opened 2018-02-11 10:39 UTC
I am referring to (1) https://github.com/gnosis/gnosis.js/ for the dev environment setup (ganache-cli and gnosis contract migration) and to (2) 
https://gnosis.github.io/gnosis.js/tutorial-developer-guide.html for the JavaScript interaction part.

I can successfully compile and migrate the gnosis-contract in my local chain (see attached console std output), import the gnosis.js library in an HTML page. I then open that webpage in the browser and operate from the WebInspector console. 

From the JS console, I can success
[ganache-cli_output.txt](https://github.com/gnosis/gnosis.js/files/1714259/ganache-cli_output.txt)
[gnosis-contract-migrate-output.txt](https://github.com/gnosis/gnosis.js/files/1714260/gnosis-contract-migrate-output.txt)

fully call the Math methods and also create on ipFs the example event in the guide. When I try to create the centralizedOracle thought, I always get an exception:

```
const oracle = await gnosis.createCentralizedOracle(ipfsHash)
utils.js:287 Uncaught (in promise) TransactionError: CentralizedOracleFactory(0xcfeb..a601).createCentralizedOracle("Qme8yRqWZd5GhDcv2rs7ibvZGfF93ddXggBLVh6aggckjn")

  failed with Error: VM Exception while processing transaction: revert Error: CentralizedOracleFactory(0xcfeb..a601).createCentralizedOracle("Qme8yRqWZd5GhDcv2rs7ibvZGfF93ddXggBLVh6aggckjn")

  failed with Error: VM Exception while processing transaction: revert
    at new TransactionError (file:///Users/marcoz/gnosis.js/dist/gnosis.js:8337:148)
    at _callee3$ (file:///Users/marcoz/gnosis.js/dist/gnosis.js:7919:31)
    at tryCatch (file:///Users/marcoz/gnosis.js/dist/gnosis.js:21746:40)
    at Generator.invoke [as _invoke] (file:///Users/marcoz/gnosis.js/dist/gnosis.js:21980:22)
    at Generator.prototype.(anonymous function) [as throw] (file:///Users/marcoz/gnosis.js/dist/gnosis.js:21798:21)
    at step (file:///Users/marcoz/gnosis.js/dist/gnosis.js:8524:30)
    at file:///Users/marcoz/gnosis.js/dist/gnosis.js:8537:13
    at <anonymous>
TransactionError @ utils.js:287
_callee3$ @ utils.js:328
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
step @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:30
Promise rejected (async)
(anonymous) @ VM138:1
async function (async)
(anonymous) @ VM138:1
(anonymous) @ VM138:1
utils.js:287 Uncaught (in promise) Error: CentralizedOracleFactory(0xcfeb..a601).createCentralizedOracle("Qme8yRqWZd5GhDcv2rs7ibvZGfF93ddXggBLVh6aggckjn")

  failed with Error: VM Exception while processing transaction: revert
    at new TransactionError (file:///Users/marcoz/gnosis.js/dist/gnosis.js:8337:148)
    at _callee3$ (file:///Users/marcoz/gnosis.js/dist/gnosis.js:7919:31)
    at tryCatch (file:///Users/marcoz/gnosis.js/dist/gnosis.js:21746:40)
    at Generator.invoke [as _invoke] (file:///Users/marcoz/gnosis.js/dist/gnosis.js:21980:22)
    at Generator.prototype.(anonymous function) [as throw] (file:///Users/marcoz/gnosis.js/dist/gnosis.js:21798:21)
    at step (file:///Users/marcoz/gnosis.js/dist/gnosis.js:8524:30)
    at file:///Users/marcoz/gnosis.js/dist/gnosis.js:8537:13
    at <anonymous>
```

And from the ganache-cli console, I see the corresponding chain error:

```
net_version
eth_sendTransaction

  Transaction: 0x1b96f3428c65b47d581ac643af8af60c1c8122fd19df131b3ef46ba7032502d6
  Gas usage: 89527
  Block Number: 14
  Block Time: Sun Feb 11 2018 11:37:22 GMT+0100 (CET)
  Runtime Error: revert
```

**Comment by cag** [comment] 2018-02-16 12:05
Ah, I was able to reproduce the error with this... hmm...

**Comment by cag** [comment] 2018-02-18 11:49
Okay, I found the issue, and it will be resolved soon. Basically, there is a `lodash-webpack-plugin` which is used to reduce the size of the final build, but its default behavior is to remove feature sets and replace them with noops such as the `collections` feature, which is to

> Support objects in “Collection” methods.

This caused a `_.forIn` call which sets default gas limits in the attached contract abstraction instances to be turned into a noop in the webpacked bundles `gnosis.js` and `gnosis.min.js`. As a result, many calls, such as the call for creating centralized oracles, will execute with not enough gas by default.

Since the frontend we are developing uses a setup with does not use the `lodash-webpack-plugin`, it doesn't face the same issue. Therefore, this fully explains the symptoms I've observed in the previous comment.

In the future, regressions for this issue could be mitigated by running the test suite against the webpacked versions of the code as well. I'll have to look into doing so at some point.

**Comment by cag** [comment] 2018-02-18 14:02
This is fixed in v1.1.2, which I will write a release note for soon.

**Comment by cag** [comment] 2018-02-27 21:23
Got the following report about this issue:

> I tried to verify your fix but I get the same error
> here what I did:
> 1. `git fetch`
> 2. `git checkout tag/v1.1.3`
> 3. `npm install` to re generate the js files
> 4. open my index.html in the browser, with the code to import the Gnosis library (I checked that the page refers to the dist/gnosis.js file just created)
> 5. from the browser js console I run again the tutorial steps as before, and I see the same error
> all this running again a local chain created freshly with ganache-cli, and after migrating again the gnosis-contracts

**Comment by cag** [comment] 2018-02-27 22:12
Could not repro, and reporter resolved this by refreshing their cache.

**Closed by cag** 2018-02-27 22:12 UTC
